### ISSUE TITLE
erro de ppsspp v9.9.1

### ISSUE THREAD

**Issue by welintonx360x** [unknownbrackets/ppsspp-report#7]
cuando abro el ppsspp dice que no soporta mi tarjeta grafica el opengl v2.0 entonces me da una occion de abrirlo con el directx3d y despues me sale un error que dice que el programa de vide abre pero falla

**Comment by unknownbrackets** [comment]
This isn't the place to report bugs in PPSSPP, and that's probably not a bug in PPSSPP.

http://forums.ppsspp.org/forumdisplay.php?fid=28

-[Unknown]
